baseURL = "https://252123.xyz/"
title = "gpchn 栖息地"
theme = "PaperMod"

locale = "zh-CN"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "gpchn"
  description = "年轻的小伙儿渴望建立功勋"

  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

  avatar = "/images/avatar.jpeg"
  assets = { favicon = "/favicon-32x32.ico", favicon16x16 = "/favicon-16x16.ico", favicon32x32 = "/favicon-32x32.ico" }

  ShowSearch = true
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true

  comments = true
  [params.giscus]
    repo = "gpchn/blog-comments"
    repoId = "R_kgDOSLoubw"
    category = "Announcements"
    categoryId = "DIC_kwDOSLoub84C7nHP" 
    mapping = "pathname"
    lang = "zh-CN"
    inputPosition = "top"
    loading = "lazy"
    theme = "preferred_color_scheme"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/archives"
  weight = 2

[[menu.main]]
  name = "搜索"
  url = "/search"
  weight = 3

[[menu.main]]
  name = "关于"
  url = "/about"
  weight = 4

[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 5
